# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               shrkey
tagline:             'Beyond the Edge'
description:         'Maker of underwater robots, hunter of treasure, teller of tales, drinker of rum, founder of @darkwaterhq and @openfloats.'
url:                 http://shrkey.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shrkey
  url:               https://twitter.com/shrkey
  email:             team@darkwater.io

# Custom vars
version:             1.0.0
